<a href="https://colab.research.google.com/github/argxsL/CCMACLRL_EXERCISES_COM231ML/blob/main/Exercise6/Exercise6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercise 6: Choosing the best performing model on a dataset

Instructions:

- Use the Dataset File to train your model
- Use the Test File to generate your results
- Use the Sample Submission file to generate the same format
- Use all Regression models

Submit your results to:
https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/overview

In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
from matplotlib import pyplot as plt
from sklearn.neighbors import KNeighborsRegressor
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split, cross_val_score

from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

## Dataset File

In [2]:
train_data = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/train.csv?raw=true'
df = pd.read_csv(train_data)

In [3]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## Test File

In [4]:
test_url = 'https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/test.csv?raw=true'
dt=pd.read_csv(test_url)

In [5]:
#dt.info()

In [6]:
df['Electrical'].value_counts()

Electrical
SBrkr    1334
FuseA      94
FuseF      27
FuseP       3
Mix         1
Name: count, dtype: int64

## Pre-processing Data

In [7]:
#df.info()

In [8]:
#df.head()

In [9]:
#df.isnull().sum().sort_values(ascending=False).head(35)

In [10]:
#dt.isnull().sum().sort_values(ascending=False).head(35)

In [11]:
columns_with_null_cat_none = [
    'Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature',
    'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
    'BsmtFinType1', 'BsmtFinType2','GarageType',
    'GarageFinish', 'GarageQual', 'GarageCond'
]

columns_with_null_cat_mode = [
    'MSZoning', 'Utilities', 'Exterior1st', 'Exterior2nd',
    'KitchenQual', 'Functional', 'SaleType', 'Electrical'
]

columns_with_null_num_zero = [
    'MasVnrArea', 'GarageYrBlt', 'BsmtFinSF1', 'BsmtFinSF2', 'BsmtUnfSF',
    'TotalBsmtSF', 'BsmtFullBath', 'BsmtHalfBath', 'GarageCars', 'GarageArea'
]

columns_with_null_num_median = [
    'LotFrontage'
]

In [12]:
for col in columns_with_null_cat_none:
    df[col].fillna('None', inplace=True)
    dt[col].fillna('None', inplace=True)

/tmp/ipython-input-2630142967.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna('None', inplace=True)
/tmp/ipython-input-2630142967.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt[col].fillna('None', inplace=True)

In [13]:
for col in columns_with_null_cat_mode:
    df[col].fillna(df[col].mode()[0], inplace=True)
    dt[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipython-input-154704745.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)
/tmp/ipython-input-154704745.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt[col].fillna(df[col].mode()[0], inplace=True)

In [14]:
for col in columns_with_null_num_zero:
    df[col].fillna(0, inplace=True)
    dt[col].fillna(0, inplace=True)

/tmp/ipython-input-1525153482.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(0, inplace=True)
/tmp/ipython-input-1525153482.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt[col].fillna(0, inplace=True)

In [15]:
for col in columns_with_null_num_median:
    df[col].fillna(df[col].median(), inplace=True)
    dt[col].fillna(df[col].median(), inplace=True)

/tmp/ipython-input-2373957663.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(), inplace=True)
/tmp/ipython-input-2373957663.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt[col].fillna(df[col].median(), inplace=True)

In [16]:
df['Electrical'].fillna(df['Electrical'].mode()[0], inplace=True)
dt['Electrical'].fillna(df['Electrical'].mode()[0], inplace=True)

/tmp/ipython-input-995407184.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dt['Electrical'].fillna(df['Electrical'].mode()[0], inplace=True)

In [17]:
#df.isnull().sum().sort_values(ascending=False).head(35)

In [18]:
#dt.isnull().sum().sort_values(ascending=False).head(35)

In [19]:
df["SaleCondition"] = [1 if each == "Normal" else 0 for each in df["SaleCondition"]]
dt["SaleCondition"] = [1 if each == "Normal" else 0 for each in dt["SaleCondition"]]

In [20]:
le = LabelEncoder()

In [21]:
df_object = df.select_dtypes('object')
dt_object = dt.select_dtypes('object')
df_object.head()

,MSZoning,Street,Alley,LotShape,LandContour,Utilities,LotConfig,LandSlope,Neighborhood,Condition1,...,FireplaceQu,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType
0,RL,Pave,None,Reg,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,None,Attchd,RFn,TA,TA,Y,None,None,None,WD
1,RL,Pave,None,Reg,Lvl,AllPub,FR2,Gtl,Veenker,Feedr,...,TA,Attchd,RFn,TA,TA,Y,None,None,None,WD
2,RL,Pave,None,IR1,Lvl,AllPub,Inside,Gtl,CollgCr,Norm,...,TA,Attchd,RFn,TA,TA,Y,None,None,None,WD
3,RL,Pave,None,IR1,Lvl,AllPub,Corner,Gtl,Crawfor,Norm,...,Gd,Detchd,Unf,TA,TA,Y,None,None,None,WD
4,RL,Pave,None,IR1,Lvl,AllPub,FR2,Gtl,NoRidge,Norm,...,TA,Attchd,RFn,TA,TA,Y,None,None,None,WD

In [22]:
for col in df_object:
    df[col] = le.fit_transform(df[col])
for col in dt_object:
    dt[col] = le.fit_transform(dt[col])

In [23]:
#df['Street'].value_counts()

In [24]:
#df.head()

In [25]:
score_list = {}

## 1. Train a KNN Regressor

In [26]:
X = df.drop("SalePrice",axis=1)
y = df["SalePrice"]

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=1,test_size=0.3)

In [27]:
knn = KNeighborsRegressor(n_neighbors=10)

knn.fit(X_train, y_train)
knn_y_pred = knn.predict(X_test)

- Perform cross validation

In [28]:
scores = cross_val_score(knn, X, y, cv=10)
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


knn_score = knn.score(X_test,y_test)
score_list["KNN Classifier"] = knn_score

0.66 accuracy with a standard deviation of 0.06

## 2. Train a SVM Regression

In [29]:
svr = SVR(kernel="rbf", C=100, epsilon=0.2)
svr.fit(X_train, y_train)
svr_y_pred = svr.predict(X_test)

- Perform cross validation

In [30]:
scores = cross_val_score(svr, X, y, cv=4)

scores
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


svr_score = svr.score(X_test,y_test)
score_list["SVR"] = svr_score

-0.02 accuracy with a standard deviation of 0.02

## 3. Train a Decision Tree Regression

In [31]:
dtr = DecisionTreeRegressor(random_state=1)
dtr.fit(X_train,y_train)
dtr_y_pred = dtr.predict(X_test)

- Perform cross validation

In [32]:
scores = cross_val_score(dtr, X, y, cv=4)

scores
print("%0.2f accuracy with a standard deviation of %0.2f" % (scores.mean(), scores.std()))


dtc_score = dtr.score(X_test,y_test)
score_list["DTC"] = dtc_score

0.70 accuracy with a standard deviation of 0.08

## 4. Train a Random Forest Regression

In [52]:
rfr = RandomForestRegressor(n_estimators=10,random_state=1)
rfr.fit(X_train,y_train)
rfr_y_pred = rfr.predict(X_test)

In [53]:
rfr_score = rfr.score(X_test,y_test)
print(rfr_score)
#score_list["RFR"] = rfr_score

0.8793701519274801

## 5. Compare all the performance of all regression models

In [35]:
score_list = list(score_list.items())

In [36]:
for alg,score in score_list:
    print(f"{alg} Score is {str(score)[:4]} ")

KNN Classifier Score is 0.62
SVR Score is -0.0
DTC Score is 0.79
RFR Score is 0.89

## Sample Submission File

In [37]:
sample_submission_url ='https://github.com/robitussin/CCMACLRL_EXERCISES/blob/3fd7d51ffd17863598ac3f44eeefc558171a5b73/dataset/house-prices-advanced-regression-techniques/sample_submission.csv?raw=true'

sf=pd.read_csv(sample_submission_url)

In [38]:
sf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1459 entries, 0 to 1458
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         1459 non-null   int64
 1   SalePrice  1459 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 22.9 KB

## 6. Generate Submission File

Choose the model that has the best performance to generate a submission file.

In [39]:
sf=pd.read_csv(sample_submission_url)
id = sf.pop('Id')
knn_y_pred = knn.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'Id': id,
    'SalePrice': knn_y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('knn_submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv

In [40]:
sf=pd.read_csv(sample_submission_url)
id = sf.pop('Id')
svr_y_pred = svr.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'Id': id,
    'SalePrice': svr_y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('svr_submission_file.csv', index=False)
print("Submission file created: submission_file.csv")

Submission file created: submission_file.csv

In [41]:
sf=pd.read_csv(sample_submission_url)
id = sf.pop('Id')
dtr_y_pred = dtr.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'Id': id,
    'SalePrice': dtr_y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('dtr_submission_file.csv', index=False)
print("Submission file created: dtr_submission_file.csv")

Submission file created: dtr_submission_file.csv

In [42]:
sf=pd.read_csv(sample_submission_url)
id = sf.pop('Id')
rfr_y_pred = rfr.predict(dt)

# Create a submission DataFrame
submission_df = pd.DataFrame({
    'Id': id,
    'SalePrice': rfr_y_pred
})

# Save the submission DataFrame to a CSV file
submission_df.to_csv('rfr_submission_file.csv', index=False)
print("Submission file created: rfr_submission_file.csv")

Submission file created: rfr_submission_file.csv